config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  namespace :admin do
    get :mailbox, to: "mailbox#index"
    post "mailbox/template_file", to: "mailbox#create_template_file"

    resources :message_templates, only: %i[show] do
      resources :messages_packages, only: %i[create] do
        get :draft_messages, on: :member
      end
    end
  end

  # Defines the root path route ("/")
  root to: "admin/dashboard#index"
end

app/controllers/admin/mailbox_controller.rb
class Admin::MailboxController < AdminController
  def index
    @presenter = Mailbox::Presenter.new
  end

  def create_template_file
    result = Mailbox::CreateMessageTemplate.default.call(request.parameters)

    if result.success?
      render json: { data: result.data }, status: :created
    elsif result.component == :contract
      render json: { errors: result.errors }, status: :unprocessable_entity
    else
      render json: { errors: result.errors }, status: :bad_request
    end
  end
end

app/views/admin/mailbox/_modal_template_file_form.html.erb
<%= render(
      "admin/shared/modal_window",
      title: t("admin.mailbox.index.form.title"),
      modal_id: "addFileTemplateModal"
    ) do %>
  <%= form_with(
        url: admin_mailbox_template_file_url,
        data: {
          controller: "admin--mailbox--configure-template",
          action: "submit->admin--mailbox--configure-template#submit"
        }
      ) do %>
    <div class="modal-body">
      <%= label_tag :name, t("admin.mailbox.index.form.labels.name"), class: "form-label" %>
      <%= text_field_tag :name, nil, class: "form-control", required: true %>
      <div class="invalid-feedback" data-error-for="name"></div>

      <%= label_tag :sheet_name, t("admin.mailbox.index.form.labels.sheet_name"), class: "form-label" %>
      <%= text_field_tag :sheet_name, presenter.default_sheet_name, class: "form-control", required: true %>
      <div class="invalid-feedback" data-error-for="sheet_name"></div>

      <%= label_tag :template, t("admin.mailbox.index.form.labels.template"), class: "form-label" %>
      <%= select_tag :template,
          options_for_select(
            t("admin.mailbox.index.form.templates").invert.to_a,
            disabled: presenter.disabled_templates,
            selected: nil
          ),
          include_blank: true,
          required: true,
          class: "form-control" %>
      <div class="invalid-feedback" data-error-for="template"></div>

      <%= label_tag :emails, t("admin.mailbox.index.form.labels.emails"), class: "form-label" %>
      <%= text_area_tag :emails, nil, class: "form-control", rows: 3 %>
      <div class="invalid-feedback" data-error-for="emails"></div>
    </div>
    <div class="modal-footer">
      <%= button_tag t("admin.mailbox.index.form.close"), type: "button", class: "btn btn-secondary",
          data: { bs_dismiss: "modal" } %>
      <%= button_tag t("admin.mailbox.index.form.submit"), type: "submit", class: "btn btn-action" %>
    </div>
  <% end %>
<% end %>

app/views/admin/mailbox/index.html.erb
<% content_for(:page_header) do %>
  <%= t("admin.mailbox.index.title") %>
<% end %>

<% content_for(:page_actions) do %>
  <%= button_tag(
        type: "button",
        class: "btn btn-action",
        data: { bs_toggle: "modal", bs_target: "#addFileTemplateModal" }
      ) do %>

    <i class="fa fa-plus"></i>
    <%= t("admin.mailbox.index.configure_template") %>
  <% end %>
<% end %>

<% if @presenter.message_templates.present? %>
  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        <b><%= t("admin.mailbox.index.messages_templates") %></b>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="col-sm-2"><%= t("admin.mailbox.index.table.headers.file") %></th>
            <th scope="col"><%= t("admin.mailbox.index.table.headers.name") %></th>
            <th scope="col"><%= t("admin.mailbox.index.table.headers.template") %></th>
          </tr>
        </thead>
        <tbody>
          <% @presenter.message_templates.each do |message_template| %>
            <tr>
              <td>
                <%= link_to(message_template.url, target: "_blank") do %>
                  <%= t("admin.mailbox.index.table.actions.open") %>
                  <i class="fa fa-external-link"></i>
                <% end %>
              </td>
              <td><%= link_to(message_template.name, admin_message_template_url(message_template.id)) %></td>
              <td><%= message_template.template %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <div class="alert alert-primary" role="alert">
    <%= t("admin.mailbox.index.no_templates_configured") %>
  </div>
<% end %>

<%= render partial: "modal_template_file_form", locals: { presenter: @presenter } %>