config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  namespace :admin do
    get :mailbox, to: "mailbox#index"
    post "mailbox/template_file", to: "mailbox#create_template_file"

    resources :message_templates, only: %i[show] do
      resources :messages_packages, only: %i[create] do
        get :draft_messages, on: :member
      end
    end
  end

  # Defines the root path route ("/")
  root to: "admin/dashboard#index"
end

app/views/admin/_header.html.erb
<div class="title-header">
  <div class="row">
    <div class="col-sm-9 d-flex align-items-center">
      <h4><%= content_for(:page_header) || t("app_name") %></h4>
    </div>
    <div class="col-sm-3 d-flex justify-content-end">
      <%= content_for(:page_actions) %>
    </div>
  </div>
  <hr>
  <div class="flash">
    <% if notice.present? %><div class="alert alert-success" role="alert"><%= notice %></div><% end %>
    <% if alert.present? %><div class="alert alert-danger" role="alert"><%= alert %></div><% end %>
  </div>
</div>

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
  <div class="container-fluid">
    <%= link_to(root_url, class: "navbar-brand") do %>
      <%= image_tag("navbar-icon.png", alt: "Logo", class: "logo") %>

      <%= t("app_name") %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav me-auto mb-2 mb-lg-0"></div>

      <li class="d-flex nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
            <i class="fa fa-user"></i>
            <%= current_user.fullname %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li>
              <%= button_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <i class="fa fa-sign-out"></i>
                <%= t("navbar.logout") %>
              <% end %>
            </li>
          </ul>
        </li>
    </div>
  </div>
</nav>

app/views/admin/_sidebar.html.erb
<nav class="sidebar navbar-expand">
  <ul class="nav navbar-nav flex-column">
    <li class="nav-item">
      <%= link_to t("sidebar.dashboard"), root_url, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to t("sidebar.mailbox"), admin_mailbox_url, class: "nav-link" %>
    </li>
  </ul>
</nav>